{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "scrolled": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting doubt\n",
      "  Downloading doubt-2.0.1-py3-none-any.whl (61 kB)\n",
      "\u001b[K     |████████████████████████████████| 61 kB 1.3 MB/s eta 0:00:011\n",
      "\u001b[?25hRequirement already satisfied: statsmodels>=0.12 in /Users/cmougan/opt/anaconda3/envs/uncertainty/lib/python3.9/site-packages (from doubt) (0.12.2)\n",
      "Requirement already satisfied: numpy>=1.20 in /Users/cmougan/opt/anaconda3/envs/uncertainty/lib/python3.9/site-packages (from doubt) (1.20.2)\n",
      "Requirement already satisfied: scikit-learn>=0.24 in /Users/cmougan/opt/anaconda3/envs/uncertainty/lib/python3.9/site-packages (from doubt) (0.24.1)\n",
      "Collecting tables>=3.6\n",
      "  Downloading tables-3.6.1.tar.gz (4.6 MB)\n",
      "\u001b[K     |████████████████████████████████| 4.6 MB 2.0 MB/s eta 0:00:01\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/cmougan/opt/anaconda3/envs/uncertainty/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-yx2f85tu/tables_4f992a2758a244368eccb9584d5ec745/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-yx2f85tu/tables_4f992a2758a244368eccb9584d5ec745/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-pip-egg-info-ux9zrech\n",
      "         cwd: /private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-yx2f85tu/tables_4f992a2758a244368eccb9584d5ec745/\n",
      "    Complete output (13 lines):\n",
      "    /var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/H5close8nmehk5o.c:2:5: warning: implicit declaration of function 'H5close' is invalid in C99 [-Wimplicit-function-declaration]\n",
      "        H5close();\n",
      "        ^\n",
      "    1 warning generated.\n",
      "    ld: library not found for -lhdf5\n",
      "    clang: error: linker command failed with exit code 1 (use -v to see invocation)\n",
      "    * Using Python 3.9.2 | packaged by conda-forge | (default, Feb 21 2021, 05:02:20)\n",
      "    * USE_PKGCONFIG: True\n",
      "    * Found conda env: ``/Users/cmougan/opt/anaconda3/envs/uncertainty``\n",
      "    .. ERROR:: Could not find a local HDF5 installation.\n",
      "       You may need to explicitly state where your local HDF5 headers and\n",
      "       library can be found by setting the ``HDF5_DIR`` environment\n",
      "       variable or by using the ``--hdf5`` command-line option.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/2b/32/847ee3f521aae6a0be380d923a736162d698586f444df1ac24b98c65025c/tables-3.6.1.tar.gz#sha256=49a972b8a7c27a8a173aeb05f67acb45fe608b64cd8e9fa667c0962a60b71b49 (from https://pypi.org/simple/tables/) (requires-python:>=3.5). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25hCollecting doubt\n",
      "  Downloading doubt-2.0.0-py3-none-any.whl (61 kB)\n",
      "\u001b[K     |████████████████████████████████| 61 kB 3.9 MB/s eta 0:00:011\n",
      "\u001b[?25h  Downloading doubt-1.2.0-py3-none-any.whl (61 kB)\n",
      "\u001b[K     |████████████████████████████████| 61 kB 5.9 MB/s  eta 0:00:01\n",
      "\u001b[?25h  Downloading doubt-1.1.0-py3-none-any.whl (61 kB)\n",
      "\u001b[K     |████████████████████████████████| 61 kB 4.4 MB/s eta 0:00:011\n",
      "\u001b[?25h  Downloading doubt-1.0.0-py3-none-any.whl (60 kB)\n",
      "\u001b[K     |████████████████████████████████| 60 kB 4.7 MB/s  eta 0:00:01\n",
      "\u001b[?25hCollecting requests\n",
      "  Using cached requests-2.25.1-py2.py3-none-any.whl (61 kB)\n",
      "Requirement already satisfied: scipy in /Users/cmougan/opt/anaconda3/envs/uncertainty/lib/python3.9/site-packages (from doubt) (1.6.2)\n",
      "Collecting openpyxl\n",
      "  Downloading openpyxl-3.0.7-py2.py3-none-any.whl (243 kB)\n",
      "\u001b[K     |████████████████████████████████| 243 kB 3.9 MB/s eta 0:00:01\n",
      "\u001b[?25hCollecting PyYAML\n",
      "  Using cached PyYAML-5.4.1-cp39-cp39-macosx_10_9_x86_64.whl (259 kB)\n",
      "Collecting tables\n",
      "  Downloading tables-3.5.2.tar.gz (7.8 MB)\n",
      "\u001b[K     |████████████████████████████████| 7.8 MB 9.6 MB/s eta 0:00:01     |██████████████████▎             | 4.5 MB 6.1 MB/s eta 0:00:01\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/cmougan/opt/anaconda3/envs/uncertainty/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-yx2f85tu/tables_24a591f5fab844349b433e08367dc816/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-yx2f85tu/tables_24a591f5fab844349b433e08367dc816/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-pip-egg-info-pawr0mnc\n",
      "         cwd: /private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-yx2f85tu/tables_24a591f5fab844349b433e08367dc816/\n",
      "    Complete output (13 lines):\n",
      "    /var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/H5closevj27hphf.c:2:5: warning: implicit declaration of function 'H5close' is invalid in C99 [-Wimplicit-function-declaration]\n",
      "        H5close();\n",
      "        ^\n",
      "    1 warning generated.\n",
      "    ld: library not found for -lhdf5\n",
      "    clang: error: linker command failed with exit code 1 (use -v to see invocation)\n",
      "    * Using Python 3.9.2 | packaged by conda-forge | (default, Feb 21 2021, 05:02:20)\n",
      "    * USE_PKGCONFIG: True\n",
      "    * Found conda env: ``/Users/cmougan/opt/anaconda3/envs/uncertainty``\n",
      "    .. ERROR:: Could not find a local HDF5 installation.\n",
      "       You may need to explicitly state where your local HDF5 headers and\n",
      "       library can be found by setting the ``HDF5_DIR`` environment\n",
      "       variable or by using the ``--hdf5`` command-line option.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/73/51/6dabb2b94826e5db3aa2542b80f1382780b96a0cd13e0cfb637b36ede5c5/tables-3.5.2.tar.gz#sha256=b220e32262bab320aa41d33125a7851ff898be97c0de30b456247508e2cc33c2 (from https://pypi.org/simple/tables/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading tables-3.5.1.tar.gz (8.3 MB)\n",
      "\u001b[K     |████████████████████████████████| 8.3 MB 4.0 MB/s eta 0:00:01\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/cmougan/opt/anaconda3/envs/uncertainty/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-yx2f85tu/tables_f3085189ed4f4125a140410fd0322d8a/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-yx2f85tu/tables_f3085189ed4f4125a140410fd0322d8a/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-pip-egg-info-jf2qyzf9\n",
      "         cwd: /private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-yx2f85tu/tables_f3085189ed4f4125a140410fd0322d8a/\n",
      "    Complete output (13 lines):\n",
      "    /var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/H5closekpw7rfzm.c:2:5: warning: implicit declaration of function 'H5close' is invalid in C99 [-Wimplicit-function-declaration]\n",
      "        H5close();\n",
      "        ^\n",
      "    1 warning generated.\n",
      "    ld: library not found for -lhdf5\n",
      "    clang: error: linker command failed with exit code 1 (use -v to see invocation)\n",
      "    * Using Python 3.9.2 | packaged by conda-forge | (default, Feb 21 2021, 05:02:20)\n",
      "    * USE_PKGCONFIG: True\n",
      "    * Found conda env: ``/Users/cmougan/opt/anaconda3/envs/uncertainty``\n",
      "    .. ERROR:: Could not find a local HDF5 installation.\n",
      "       You may need to explicitly state where your local HDF5 headers and\n",
      "       library can be found by setting the ``HDF5_DIR`` environment\n",
      "       variable or by using the ``--hdf5`` command-line option.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/c6/e6/38cdcdc501ff889ea1e60bd5ef61d0573f73606f4dd0169786fd991c6b70/tables-3.5.1.tar.gz#sha256=88e2f3be1f143febc8bf8a7fe49ad51fc12518d6a1ac4eb641778d93e5dc2039 (from https://pypi.org/simple/tables/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[?25h  Downloading tables-3.4.4.tar.gz (4.6 MB)\n",
      "\u001b[K     |████████████████████████████████| 4.6 MB 7.9 MB/s eta 0:00:01\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/cmougan/opt/anaconda3/envs/uncertainty/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-yx2f85tu/tables_17192975f242456f9954c0b2d781b491/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-yx2f85tu/tables_17192975f242456f9954c0b2d781b491/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-pip-egg-info-y_m5b4vq\n",
      "         cwd: /private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-yx2f85tu/tables_17192975f242456f9954c0b2d781b491/\n",
      "    Complete output (13 lines):\n",
      "    /var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/H5closecg1et5t4.c:2:5: warning: implicit declaration of function 'H5close' is invalid in C99 [-Wimplicit-function-declaration]\n",
      "        H5close();\n",
      "        ^\n",
      "    1 warning generated.\n",
      "    ld: library not found for -lhdf5\n",
      "    clang: error: linker command failed with exit code 1 (use -v to see invocation)\n",
      "    * Using Python 3.9.2 | packaged by conda-forge | (default, Feb 21 2021, 05:02:20)\n",
      "    * USE_PKGCONFIG: True\n",
      "    * Found conda env: ``/Users/cmougan/opt/anaconda3/envs/uncertainty``\n",
      "    .. ERROR:: Could not find a local HDF5 installation.\n",
      "       You may need to explicitly state where your local HDF5 headers and\n",
      "       library can be found by setting the ``HDF5_DIR`` environment\n",
      "       variable or by using the ``--hdf5`` command-line option.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/4d/53/8f34ce887c2a2ad80518980419a5f6f41defc85a287a355987e559ce9385/tables-3.4.4.tar.gz#sha256=bdc5c073712af2a43babd139c4855fc99496bb2c3f3f5d1b4770a985e6f9ce29 (from https://pypi.org/simple/tables/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading tables-3.4.3.tar.gz (4.6 MB)\n",
      "\u001b[K     |████████████████████████████████| 4.6 MB 3.5 MB/s eta 0:00:01\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/cmougan/opt/anaconda3/envs/uncertainty/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-yx2f85tu/tables_3f5886cb139c41e88d1329a9b474378f/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-yx2f85tu/tables_3f5886cb139c41e88d1329a9b474378f/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-pip-egg-info-timm420c\n",
      "         cwd: /private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-yx2f85tu/tables_3f5886cb139c41e88d1329a9b474378f/\n",
      "    Complete output (13 lines):\n",
      "    /var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/H5closem51_maor.c:2:5: warning: implicit declaration of function 'H5close' is invalid in C99 [-Wimplicit-function-declaration]\n",
      "        H5close();\n",
      "        ^\n",
      "    1 warning generated.\n",
      "    ld: library not found for -lhdf5\n",
      "    clang: error: linker command failed with exit code 1 (use -v to see invocation)\n",
      "    * Using Python 3.9.2 | packaged by conda-forge | (default, Feb 21 2021, 05:02:20)\n",
      "    * USE_PKGCONFIG: True\n",
      "    * Found conda env: ``/Users/cmougan/opt/anaconda3/envs/uncertainty``\n",
      "    .. ERROR:: Could not find a local HDF5 installation.\n",
      "       You may need to explicitly state where your local HDF5 headers and\n",
      "       library can be found by setting the ``HDF5_DIR`` environment\n",
      "       variable or by using the ``--hdf5`` command-line option.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/98/bb/0192955689d2e5972e2714300433eff57e5bef4147248cb15c7b6f04ae9e/tables-3.4.3.tar.gz#sha256=b6aafe47154e2140c0a91bb38ebdb6ba67a24dd86263f1c294af8c11cb7deed4 (from https://pypi.org/simple/tables/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading tables-3.4.2.tar.gz (7.6 MB)\n",
      "\u001b[K     |████████████████████████████████| 7.6 MB 5.3 MB/s eta 0:00:01\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/cmougan/opt/anaconda3/envs/uncertainty/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-yx2f85tu/tables_dbe3f7564aa24ad2ba86019be560609a/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-yx2f85tu/tables_dbe3f7564aa24ad2ba86019be560609a/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-pip-egg-info-imh6vvp4\n",
      "         cwd: /private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-yx2f85tu/tables_dbe3f7564aa24ad2ba86019be560609a/\n",
      "    Complete output (13 lines):\n",
      "    /var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/H5closeawqk69q4.c:2:5: warning: implicit declaration of function 'H5close' is invalid in C99 [-Wimplicit-function-declaration]\n",
      "        H5close();\n",
      "        ^\n",
      "    1 warning generated.\n",
      "    ld: library not found for -lhdf5\n",
      "    clang: error: linker command failed with exit code 1 (use -v to see invocation)\n",
      "    * Using Python 3.9.2 | packaged by conda-forge | (default, Feb 21 2021, 05:02:20)\n",
      "    * USE_PKGCONFIG: True\n",
      "    * Found conda env: ``/Users/cmougan/opt/anaconda3/envs/uncertainty``\n",
      "    .. ERROR:: Could not find a local HDF5 installation.\n",
      "       You may need to explicitly state where your local HDF5 headers and\n",
      "       library can be found by setting the ``HDF5_DIR`` environment\n",
      "       variable or by using the ``--hdf5`` command-line option.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/a2/e5/697f7ec96c4808983711635ef2e4c6b217493343938410125bcece1642cf/tables-3.4.2.tar.gz#sha256=fdbbea4edb6bad0ac0e53fc7bc6970e78e12eef4944aa4146bcdcb573201676c (from https://pypi.org/simple/tables/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading tables-3.4.1.tar.gz (7.6 MB)\n",
      "\u001b[K     |████████████████████████████████| 7.6 MB 6.3 MB/s eta 0:00:01     |███████████▉                    | 2.8 MB 8.1 MB/s eta 0:00:01\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/cmougan/opt/anaconda3/envs/uncertainty/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-yx2f85tu/tables_e0dfa4dd82054f68ba9991ba293d8642/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-yx2f85tu/tables_e0dfa4dd82054f68ba9991ba293d8642/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-pip-egg-info-nfvbmbcx\n",
      "         cwd: /private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-yx2f85tu/tables_e0dfa4dd82054f68ba9991ba293d8642/\n",
      "    Complete output (12 lines):\n",
      "    /var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/H5closehhl5hffs.c:2:5: warning: implicit declaration of function 'H5close' is invalid in C99 [-Wimplicit-function-declaration]\n",
      "        H5close();\n",
      "        ^\n",
      "    1 warning generated.\n",
      "    ld: library not found for -lhdf5\n",
      "    clang: error: linker command failed with exit code 1 (use -v to see invocation)\n",
      "    * Using Python 3.9.2 | packaged by conda-forge | (default, Feb 21 2021, 05:02:20)\n",
      "    * USE_PKGCONFIG: True\n",
      "    .. ERROR:: Could not find a local HDF5 installation.\n",
      "       You may need to explicitly state where your local HDF5 headers and\n",
      "       library can be found by setting the ``HDF5_DIR`` environment\n",
      "       variable or by using the ``--hdf5`` command-line option.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/d9/e6/c026063429571f0538bab59166a45bb1b0453217be3f1510aada02741b32/tables-3.4.1.tar.gz#sha256=1587337593133b169d73bc68729b2cb736a3494f93a54188b8cc26f52cd51c67 (from https://pypi.org/simple/tables/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[?25h  Downloading tables-3.4.0.tar.gz (7.6 MB)\n",
      "\u001b[K     |████████████████████████████████| 7.6 MB 521 kB/s eta 0:00:01\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/cmougan/opt/anaconda3/envs/uncertainty/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-yx2f85tu/tables_ca0229bb25624a6cb9a032f31caa79d7/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-yx2f85tu/tables_ca0229bb25624a6cb9a032f31caa79d7/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-pip-egg-info-pr0o9uov\n",
      "         cwd: /private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-yx2f85tu/tables_ca0229bb25624a6cb9a032f31caa79d7/\n",
      "    Complete output (12 lines):\n",
      "    /var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/H5close55ycy_vr.c:2:5: warning: implicit declaration of function 'H5close' is invalid in C99 [-Wimplicit-function-declaration]\n",
      "        H5close();\n",
      "        ^\n",
      "    1 warning generated.\n",
      "    ld: library not found for -lhdf5\n",
      "    clang: error: linker command failed with exit code 1 (use -v to see invocation)\n",
      "    * Using Python 3.9.2 | packaged by conda-forge | (default, Feb 21 2021, 05:02:20)\n",
      "    * USE_PKGCONFIG: True\n",
      "    .. ERROR:: Could not find a local HDF5 installation.\n",
      "       You may need to explicitly state where your local HDF5 headers and\n",
      "       library can be found by setting the ``HDF5_DIR`` environment\n",
      "       variable or by using the ``--hdf5`` command-line option.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/59/fb/ac97f34f6cd1863a4a7709fc0dd907efcfe5d10adeba152f20d5e5897d08/tables-3.4.0.tar.gz#sha256=bdd1e3a55b9bfe1c518c874fc730ac34ca42ff7d505e6947229f8a9e5572cac4 (from https://pypi.org/simple/tables/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading tables-3.3.0.tar.gz (7.0 MB)\n",
      "\u001b[K     |████████████████████████████████| 7.0 MB 171 kB/s eta 0:00:01\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/cmougan/opt/anaconda3/envs/uncertainty/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-yx2f85tu/tables_539e70b978014223bf73b21e9c9ee16a/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-yx2f85tu/tables_539e70b978014223bf73b21e9c9ee16a/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-pip-egg-info-j94tqpu_\n",
      "         cwd: /private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-yx2f85tu/tables_539e70b978014223bf73b21e9c9ee16a/\n",
      "    Complete output (12 lines):\n",
      "    /var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/H5close5zvdc5g9.c:2:5: warning: implicit declaration of function 'H5close' is invalid in C99 [-Wimplicit-function-declaration]\n",
      "        H5close();\n",
      "        ^\n",
      "    1 warning generated.\n",
      "    ld: library not found for -lhdf5\n",
      "    clang: error: linker command failed with exit code 1 (use -v to see invocation)\n",
      "    * Using Python 3.9.2 | packaged by conda-forge | (default, Feb 21 2021, 05:02:20)\n",
      "    * USE_PKGCONFIG: True\n",
      "    .. ERROR:: Could not find a local HDF5 installation.\n",
      "       You may need to explicitly state where your local HDF5 headers and\n",
      "       library can be found by setting the ``HDF5_DIR`` environment\n",
      "       variable or by using the ``--hdf5`` command-line option.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/97/eb/ea2102f5a210a62f9f7387cf9912cb841f4a9089dbb232e642daa2626769/tables-3.3.0.tar.gz#sha256=8383ccf02e041a5d55494a09fc5514140b4653055a2732c981b5fd0f7408822c (from https://pypi.org/simple/tables/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading tables-3.2.3.1.tar.gz (7.1 MB)\n",
      "\u001b[K     |████████████████████████████████| 7.1 MB 6.5 MB/s eta 0:00:01\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/cmougan/opt/anaconda3/envs/uncertainty/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-yx2f85tu/tables_acd5bdfa942242d2b0b69547f4b70af3/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-yx2f85tu/tables_acd5bdfa942242d2b0b69547f4b70af3/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-pip-egg-info-qzxb3we6\n",
      "         cwd: /private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-yx2f85tu/tables_acd5bdfa942242d2b0b69547f4b70af3/\n",
      "    Complete output (12 lines):\n",
      "    /var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/H5closekn1byfzw.c:2:5: warning: implicit declaration of function 'H5close' is invalid in C99 [-Wimplicit-function-declaration]\n",
      "        H5close();\n",
      "        ^\n",
      "    1 warning generated.\n",
      "    ld: library not found for -lhdf5\n",
      "    clang: error: linker command failed with exit code 1 (use -v to see invocation)\n",
      "    * Using Python 3.9.2 | packaged by conda-forge | (default, Feb 21 2021, 05:02:20)\n",
      "    * USE_PKGCONFIG: True\n",
      "    .. ERROR:: Could not find a local HDF5 installation.\n",
      "       You may need to explicitly state where your local HDF5 headers and\n",
      "       library can be found by setting the ``HDF5_DIR`` environment\n",
      "       variable or by using the ``--hdf5`` command-line option.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/0c/eb/e2def4cefade4b2427b8737b7c67cd00db8746dbb02dbfcf66a010f13954/tables-3.2.3.1.tar.gz#sha256=20fb453dcfbb28450f4f738ed8ce85943b1cca4bf5e3cd739098cae6dac9dbc8 (from https://pypi.org/simple/tables/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading tables-3.2.3.tar.gz (7.1 MB)\n",
      "\u001b[K     |████████████████████████████████| 7.1 MB 4.7 MB/s eta 0:00:01\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/cmougan/opt/anaconda3/envs/uncertainty/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-yx2f85tu/tables_174276338a5842d682f8a5e79a8bdc78/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-yx2f85tu/tables_174276338a5842d682f8a5e79a8bdc78/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-pip-egg-info-vqtdcj16\n",
      "         cwd: /private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-yx2f85tu/tables_174276338a5842d682f8a5e79a8bdc78/\n",
      "    Complete output (5 lines):\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-yx2f85tu/tables_174276338a5842d682f8a5e79a8bdc78/setup.py\", line 34, in <module>\n",
      "        import cpuinfo\n",
      "    ModuleNotFoundError: No module named 'cpuinfo'\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/bd/a5/b6466e504397cbb64bc12075c884b86e2e65c73e007c14048bafb87c6ae2/tables-3.2.3.tar.gz#sha256=c9d4f86f465b18a0fe57d03df17534e26760d9af5d1440bcb86a0189c2cb0639 (from https://pypi.org/simple/tables/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[?25h  Downloading tables-3.2.2.tar.gz (7.0 MB)\n",
      "\u001b[K     |████████████████████████████████| 7.0 MB 5.5 MB/s eta 0:00:01\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/cmougan/opt/anaconda3/envs/uncertainty/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-yx2f85tu/tables_c54e50bedfe84678a51ad950fba47c21/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-yx2f85tu/tables_c54e50bedfe84678a51ad950fba47c21/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-pip-egg-info-dslmam3a\n",
      "         cwd: /private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-yx2f85tu/tables_c54e50bedfe84678a51ad950fba47c21/\n",
      "    Complete output (12 lines):\n",
      "    /var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/H5close4u7i3kvp.c:2:5: warning: implicit declaration of function 'H5close' is invalid in C99 [-Wimplicit-function-declaration]\n",
      "        H5close();\n",
      "        ^\n",
      "    1 warning generated.\n",
      "    ld: library not found for -lhdf5\n",
      "    clang: error: linker command failed with exit code 1 (use -v to see invocation)\n",
      "    * Using Python 3.9.2 | packaged by conda-forge | (default, Feb 21 2021, 05:02:20)\n",
      "    * USE_PKGCONFIG: True\n",
      "    .. ERROR:: Could not find a local HDF5 installation.\n",
      "       You may need to explicitly state where your local HDF5 headers and\n",
      "       library can be found by setting the ``HDF5_DIR`` environment\n",
      "       variable or by using the ``--hdf5`` command-line option.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/af/38/85a4581084ad2aaed4318b7f3a46c5bed3ecb32bae0929add5d7c752d8fc/tables-3.2.2.tar.gz#sha256=3564b351a71ec1737b503b001eb7ceae1f65d5d6e3ffe1ea75aafba10f37fa84 (from https://pypi.org/simple/tables/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading tables-3.2.1.1.tar.gz (7.0 MB)\n",
      "\u001b[K     |████████████████████████████████| 7.0 MB 6.1 MB/s eta 0:00:01     |██████████████████████████████  | 6.6 MB 6.2 MB/s eta 0:00:01\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/cmougan/opt/anaconda3/envs/uncertainty/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-yx2f85tu/tables_fc4a26e50f524c138290496888230ea2/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-yx2f85tu/tables_fc4a26e50f524c138290496888230ea2/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-pip-egg-info-zlu_8cto\n",
      "         cwd: /private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-yx2f85tu/tables_fc4a26e50f524c138290496888230ea2/\n",
      "    Complete output (12 lines):\n",
      "    /var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/H5closenpiy4kgb.c:2:5: warning: implicit declaration of function 'H5close' is invalid in C99 [-Wimplicit-function-declaration]\n",
      "        H5close();\n",
      "        ^\n",
      "    1 warning generated.\n",
      "    ld: library not found for -lhdf5\n",
      "    clang: error: linker command failed with exit code 1 (use -v to see invocation)\n",
      "    * Using Python 3.9.2 | packaged by conda-forge | (default, Feb 21 2021, 05:02:20)\n",
      "    * USE_PKGCONFIG: True\n",
      "    .. ERROR:: Could not find a local HDF5 installation.\n",
      "       You may need to explicitly state where your local HDF5 headers and\n",
      "       library can be found by setting the ``HDF5_DIR`` environment\n",
      "       variable or by using the ``--hdf5`` command-line option.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/5e/25/2591b0a60b16c9e65f1a0480dfc756e38c92aa714f9936dd07e965276409/tables-3.2.1.1.tar.gz#sha256=21e9749a60c6acc8a9755a52d95b414bc4f4b2c72a9175af360225883a775358 (from https://pypi.org/simple/tables/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading tables-3.2.0.tar.gz (7.0 MB)\n",
      "\u001b[K     |████████████████████████████████| 7.0 MB 4.9 MB/s eta 0:00:01\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/cmougan/opt/anaconda3/envs/uncertainty/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-yx2f85tu/tables_113bd7d62f6f49a7b3688f6a88a5ff11/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-yx2f85tu/tables_113bd7d62f6f49a7b3688f6a88a5ff11/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-pip-egg-info-55opuyjv\n",
      "         cwd: /private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-yx2f85tu/tables_113bd7d62f6f49a7b3688f6a88a5ff11/\n",
      "    Complete output (12 lines):\n",
      "    /var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/H5closeszr3v1be.c:2:5: warning: implicit declaration of function 'H5close' is invalid in C99 [-Wimplicit-function-declaration]\n",
      "        H5close();\n",
      "        ^\n",
      "    1 warning generated.\n",
      "    ld: library not found for -lhdf5\n",
      "    clang: error: linker command failed with exit code 1 (use -v to see invocation)\n",
      "    * Using Python 3.9.2 | packaged by conda-forge | (default, Feb 21 2021, 05:02:20)\n",
      "    * USE_PKGCONFIG: True\n",
      "    .. ERROR:: Could not find a local HDF5 installation.\n",
      "       You may need to explicitly state where your local HDF5 headers and\n",
      "       library can be found by setting the ``HDF5_DIR`` environment\n",
      "       variable or by using the ``--hdf5`` command-line option.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/92/3a/a0fd93a68b98ad2ab788f4f725250515ad2f12c23858f3b8d2b17af454a4/tables-3.2.0.tar.gz#sha256=60980e44676bfe463cdd2582ecdacc0b0763b259477015e866f8af72b4cdba44 (from https://pypi.org/simple/tables/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading tables-3.1.1.tar.gz (6.7 MB)\n",
      "\u001b[K     |████████████████████████████████| 6.7 MB 4.2 MB/s eta 0:00:01\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/cmougan/opt/anaconda3/envs/uncertainty/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-yx2f85tu/tables_858562c8ae634390aab45675dfc28360/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-yx2f85tu/tables_858562c8ae634390aab45675dfc28360/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-pip-egg-info-ww85wyqp\n",
      "         cwd: /private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-yx2f85tu/tables_858562c8ae634390aab45675dfc28360/\n",
      "    Complete output (2 lines):\n",
      "    * Using Python 3.9.2 | packaged by conda-forge | (default, Feb 21 2021, 05:02:20)\n",
      "    .. ERROR:: You need numpy 1.4.1 or greater to run PyTables!\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/69/db/2c5544686baace15d2e7f3c2363ba865049985cede70d55d7e883240b73d/tables-3.1.1.tar.gz#sha256=39b9036376f1185599771c19276f13b5b9119d98f9108f58595745ded3fe2da3 (from https://pypi.org/simple/tables/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading tables-3.1.0.tar.gz (6.7 MB)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[K     |████████████████████████████████| 6.7 MB 6.8 MB/s eta 0:00:01\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/cmougan/opt/anaconda3/envs/uncertainty/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-yx2f85tu/tables_90cb1a6f0a7d4a2b876f0518e6dea7f5/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-yx2f85tu/tables_90cb1a6f0a7d4a2b876f0518e6dea7f5/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-pip-egg-info-nanqyqra\n",
      "         cwd: /private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-yx2f85tu/tables_90cb1a6f0a7d4a2b876f0518e6dea7f5/\n",
      "    Complete output (2 lines):\n",
      "    * Using Python 3.9.2 | packaged by conda-forge | (default, Feb 21 2021, 05:02:20)\n",
      "    .. ERROR:: You need numpy 1.4.1 or greater to run PyTables!\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/b3/31/d0d47c6187d6dd9594ef165f8dd7252670c9d3c00a546bd5e56f38061a71/tables-3.1.0.tar.gz#sha256=92bd5052c61fef3d55505dcb1162150ea5e274b76c4e41633e8f78a9ad5f4dc1 (from https://pypi.org/simple/tables/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading tables-3.0.0.tar.gz (6.2 MB)\n",
      "\u001b[K     |████████████████████████████████| 6.2 MB 2.8 MB/s eta 0:00:01\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/cmougan/opt/anaconda3/envs/uncertainty/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-yx2f85tu/tables_1c7f832c9d4f438080c7d6d1cf16a739/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-yx2f85tu/tables_1c7f832c9d4f438080c7d6d1cf16a739/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-pip-egg-info-wg9xa9zl\n",
      "         cwd: /private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-yx2f85tu/tables_1c7f832c9d4f438080c7d6d1cf16a739/\n",
      "    Complete output (2 lines):\n",
      "    * Using Python 3.9.2 | packaged by conda-forge | (default, Feb 21 2021, 05:02:20)\n",
      "    .. ERROR:: You need numpy 1.4.1 or greater to run PyTables!\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/eb/e6/49cd67bd44033013e4ca5588c53dcf052e08a25befd3be1e08eba32f1a69/tables-3.0.0.tar.gz#sha256=53532a59c8f03c3c5ef3c73c04f5bfd8384d6a3d508683cb87fc17af4c71dfe1 (from https://pypi.org/simple/tables/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading tables-2.4.0.tar.gz (8.9 MB)\n",
      "\u001b[K     |████████████████████████████████| 8.9 MB 8.3 MB/s eta 0:00:01     |█████████████████████████       | 7.0 MB 8.3 MB/s eta 0:00:01\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/cmougan/opt/anaconda3/envs/uncertainty/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-yx2f85tu/tables_230afb38f94b465e8d42cabdcced16b4/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-yx2f85tu/tables_230afb38f94b465e8d42cabdcced16b4/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-pip-egg-info-ibl35d8p\n",
      "         cwd: /private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-yx2f85tu/tables_230afb38f94b465e8d42cabdcced16b4/\n",
      "    Complete output (6 lines):\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-yx2f85tu/tables_230afb38f94b465e8d42cabdcced16b4/setup.py\", line 37\n",
      "        print \".. %s:: %s\" % (kind.upper(), head)\n",
      "              ^\n",
      "    SyntaxError: invalid syntax\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/2f/04/939d8eab5c005215a6c267639006c68ddf5069d87f8946350aae60a16dab/tables-2.4.0.tar.gz#sha256=2bda3b1ffbe20ee35d5337d97071ff4177a7742b15e7837324ae7c5720e82678 (from https://pypi.org/simple/tables/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading tables-2.3.1.tar.gz (8.8 MB)\n",
      "\u001b[K     |████████████████████████████████| 8.8 MB 4.1 MB/s eta 0:00:01\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/cmougan/opt/anaconda3/envs/uncertainty/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-yx2f85tu/tables_cee4665ffe3247348231338732e4c89e/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-yx2f85tu/tables_cee4665ffe3247348231338732e4c89e/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-pip-egg-info-xp3o_rx_\n",
      "         cwd: /private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-yx2f85tu/tables_cee4665ffe3247348231338732e4c89e/\n",
      "    Complete output (6 lines):\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-yx2f85tu/tables_cee4665ffe3247348231338732e4c89e/setup.py\", line 36\n",
      "        print \".. %s:: %s\" % (kind.upper(), head)\n",
      "              ^\n",
      "    SyntaxError: invalid syntax\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/58/98/43d8e93ccb6fdae2108f1b42b4f94d396d2f97372b7741237c2fe2e7671a/tables-2.3.1.tar.gz#sha256=6b2992c163219af3b75496271f1645e98705e51df6fb5daeaf83b9eae6b371cc (from https://pypi.org/simple/tables/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading tables-2.3.tar.gz (8.8 MB)\n",
      "\u001b[K     |████████████████████████████████| 8.8 MB 5.5 MB/s eta 0:00:01\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/cmougan/opt/anaconda3/envs/uncertainty/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-yx2f85tu/tables_f746927d1551463aa6e52e49a858b209/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-yx2f85tu/tables_f746927d1551463aa6e52e49a858b209/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-pip-egg-info-k83r2jmq\n",
      "         cwd: /private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-yx2f85tu/tables_f746927d1551463aa6e52e49a858b209/\n",
      "    Complete output (6 lines):\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-yx2f85tu/tables_f746927d1551463aa6e52e49a858b209/setup.py\", line 36\n",
      "        print \".. %s:: %s\" % (kind.upper(), head)\n",
      "              ^\n",
      "    SyntaxError: invalid syntax\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/6f/65/44351a6a80aeae9548e0d638acdfa393b2d5158c5287620ec2b7704d41be/tables-2.3.tar.gz#sha256=d7350b47a9bbf832693700e6c247967f1e289f1b8be71c593cfe1558f94a9e79 (from https://pypi.org/simple/tables/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[31mERROR: Cannot install doubt==1.0.0, doubt==1.1.0, doubt==1.2.0, doubt==2.0.0 and doubt==2.0.1 because these package versions have conflicting dependencies.\u001b[0m\n",
      "\u001b[?25h\n",
      "The conflict is caused by:\n",
      "    doubt 2.0.1 depends on tables>=3.6\n",
      "    doubt 2.0.0 depends on tables>=3.6\n",
      "    doubt 1.2.0 depends on tables>=3.6\n",
      "    doubt 1.1.0 depends on tables>=3.6\n",
      "    doubt 1.0.0 depends on tables\n",
      "\n",
      "To fix this you could try to:\n",
      "1. loosen the range of package versions you've specified\n",
      "2. remove package versions to allow pip attempt to solve the dependency conflict\n",
      "\n",
      "\u001b[31mERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies\u001b[0m\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install doubt"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "uncertainty",
   "language": "python",
   "name": "uncertainty"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
